### PR TITLE
Marlin support

### LINKED ISSUE #5: Marlin controller type missing
Can tinyweb add support for marlin based controllers?

### PR DESCRIPTION
**Pull request by johnboiles**
I _think_ this is what would be required for Marlin support. Fixes #5

### CODE REVIEW

**Comment by MitchBradley** [comment]
I suspect that you also need mods to app.js to add a "controller.on('Marlin:state'" .. function, and perhaps a 'Marlin:settings' function too.

**Comment by johnboiles** [comment]
Hmm nevermind I guess I need some more JS changes.. this is a start

**Comment by MitchBradley** [comment]
You are on the right track

**Comment by johnboiles** [comment]
Ok kinda working on my mpcnc now, but I need to find a cleaner way to change the G0 command because I bet this breaks other machines

**Comment by MitchBradley** [comment]
The G0 change looks fine.  I presume it is because Marlin does not support G91 and G0 on the same line?

You might be able to get a more-nuanced value for stateText from the modal.program property.  It's value seems to be one of M0, M1, M2, M30.  M0 and M1 would imply Pause state, M2 and M30 would be PgmEnd state.  I'm not sure what the modal.program property value is for run and idle states.  Perhaps the empty string, or null, or maybe it is sticky at the last value. Marlin is not very forthcoming about reporting its internal state; it appears that cncjs infers the state by parsing the GCode that is sent to Marlin.

**Comment by johnboiles** [comment]
> I presume it is because Marlin does not support G91 and G0 on the same line?

I assume so! I just saw it was different than what I could definitely make work in the console and made the change.

> You might be able to get a more-nuanced value for stateText from the modal.program property

Cool I'll take a look at that. I could probably also dig for the corresponding code in cnc.js. Do you know off the top of your head where that is?

**Comment by johnboiles** [comment]
@MitchBradley I've been using this for a bit and it seems to all work. What do you think about merging? The CI failures look like CI issues, not problems with this code but correct me if I'm wrong

**Comment by johnboiles** [comment]
Also, I tried using `modal.program` and it seemed to always return M0 for me

**Comment by MitchBradley** [comment]
I'm not the maintainer of this subproject but I do have commit privileges.  I'll ask @cheton what he thinks about my taking some responsibility.

**Comment by cheton** [comment]
@johnboiles 
Thank you for reminding me. I have to manage issues across multiple GitHub repositories, I may occasionally miss something. This pull request looks good to me, I will merge it to the master branch.

@MitchBradley 
You can help commit code or merge PR if you don't find any critical issues to it. Thank you. 😃

**Comment by cheton** [comment]
> Also, I tried using modal.program and it seemed to always return M0 for me

@johnboiles 
Marlin does not support status report for modal state. It's internally done in the Marlin controller in CNCjs by interpreting each line:

https://github.com/cncjs/cncjs/blob/master/src/app/controllers/Marlin/MarlinController.js#L236-L323

Currently I don't have a board running Marlin on hand. You can help check if it works as expected.

**Comment by johnboiles** [comment]
Interesting. In my testing I only ever saw it as M0 but totally possible that’s all my gcode ever set. I’ll have to take a look.

Would it make sense to use cncjs’s state for the top text bar instead? Something like ‘Running’ if it’s processing gcode, or ‘Paused’, etc?

**Comment by MitchBradley** [comment]
When I get a break from my current project (motorizing a bottle labeler using an ESP8266 driving a stepper), I'll try loading Marlin on a Teensy and see how it behaves.

**Comment by MitchBradley** [comment]
I got Marlin 2.0 running on both Teensy 3.1 and ESP-32.  No motors or other peripherals, but I can send GCode and query position etc.  If you have Marlin patches to cncjs-shopfloor-tablet, I can now test them.

**Pull request merged**
